// @ts-check
import { defineConfig } from 'astro/config';

// Static output. Cloudflare Pages serves dist/ (build: npm run build).
// The data layer is books.json today; it is kept separable so a live
// repo-backed source can sit beside it later for the Studio.
// The sitemap is generated by src/pages/sitemap.xml.ts (a small endpoint we
// control), which keeps the private /studio route out of it.
export default defineConfig({
  site: 'https://murmmers.com',
});
